### ISSUE TITLE
Error while starting up.

### ISSUE THREAD

**Issue by mechmind** [tlrobinson/narwhal-v8#2]
I have built narwhal-v8 under linux and switched narwhal engine to v8. Then, i got an error:

> $ narwhal
> REQUIRE: id[global] baseId[undefined] pkg[undefined] basePkg[undefined]
> USING: id[global] pkg[null]
> \ global
> REQUIRE: id[./global-es5] baseId[global] pkg[undefined] basePkg[null]
> USING: id[global-es5] pkg[null]
> \ global-es5
> REQUIRE: id[json] baseId[global-es5] pkg[undefined] basePkg[null]
> USING: id[json] pkg[null]
> \ json
> /// json
> // global-es5
> REQUIRE: id[./global-commonjs] baseId[global] pkg[undefined] basePkg[null]
> USING: id[global-commonjs] pkg[null]
> \ global-commonjs
> REQUIRE: id[global-es5] baseId[global-commonjs] pkg[undefined] basePkg[null]
> USING: id[global-es5] pkg[null]
> // global-commonjs
> / global
> REQUIRE: id[file] baseId[undefined] pkg[undefined] basePkg[undefined]
> USING: id[file] pkg[null]
> \ file
> REQUIRE: id[io] baseId[file] pkg[undefined] basePkg[null]
> USING: id[io] pkg[null]
> \ io
> REQUIRE: id[io-engine] baseId[io] pkg[undefined] basePkg[null]
> USING: id[io-engine] pkg[null]
> \ io-engine
> REQUIRE: id[io-engine] baseId[io-engine] pkg[undefined] basePkg[null]
> USING: id[io-engine] pkg[null]
> REQUIRE: id[binary] baseId[io-engine] pkg[undefined] basePkg[null]
> USING: id[binary] pkg[null]
> \ binary
> REQUIRE: id[binary-engine] baseId[binary] pkg[undefined] basePkg[null]
> USING: id[binary-engine] pkg[null]
> \\ binary-engine
> ///// binary-engine
> //// binary
> REQUIRE: id[binary-engine] baseId[io-engine] pkg[undefined] basePkg[null]
> USING: id[binary-engine] pkg[null]
> undefined:7: TypeError: Cannot read property 'prototype' of undefined
> exports.IO.prototype.copy = function (output, mode, options) {
>          ^
> Error executing bootstrap.js from >/home/mechmind/work/tools/narwhal/packages/narwhal-v8/bootstrap.js

Also i modified Makefile, and it looks like this: 

> CPP       =g++
> CPPFLAGS  =-g #-save-temps
> INCLUDES  =-Iv8/include -Iinclude -I/usr/include
> LIBS      =-lreadline -L/usr/lib -L/home/mechmind/work/tools/lib/ -Lv8 -liconv -ldl -lv8 -Wl,--rpath,/home/mechmind/work/tools/lib/
> MODULES   =$(patsubst %.cc,%.so,$(patsubst src/%,lib/%,$(wildcard src/*.cc)))
> # change to libv8_g.dylib for debug version:
> 
> V8NAME    =libv8.so
> # V8NAME    =libv8_g.dylib
> 
> V8        =v8/$(V8NAME)
> 
> all: $(V8) bin/narwhal-v8 modules
> 
> modules: $(MODULES)
> 
> bin/narwhal-v8: narwhal-v8.cc $(V8)
>   mkdir -p bin
>   $(CPP) $(CPPFLAGS) $(INCLUDES) -o $@ narwhal-v8.cc  $(LIBS)
>   # comment out these lines to use installed system V8
>   #install_name_tool -change "$(V8NAME)" "@executable_path/$(V8NAME)" $@
>   cp $(V8) lib/$(V8NAME)
> 
> lib/%.so: src/%.cc
>   mkdir -p lib
>   $(CPP) $(CPPFLAGS) $(INCLUDES) -shared -o $@ $< $(V8) $(LIBS)
>   # comment out these lines to use installed system V8
> # install_name_tool -change "$(V8NAME)" "@executable_path/$(V8NAME)" $@
> 
> v8/libv8.so: v8
>   cd v8 && scons library=shared
> # v8/libv8_g.dylib: v8
> # cd v8 && scons library=shared mode=debug
> 
> v8:
>   svn checkout http://v8.googlecode.com/svn/trunk/ v8
> 
> clean:
>   rm -rf bin/narwhal-v8 bin/_.dylib bin/_.dSYM lib/_.dylib lib/_.dSYM *.o *.ii *.s
> 
> cleaner: clean
>   rm -rf v8/$(V8NAME)
>   cd v8 && scons -c . library=shared
> 
> pristine: clean
>   rm -rf v8
> 
> install: all
>   mkdir -p /home/mechmind/work/tools/narwhal/engines/v8
>   cp -r bin lib package.json bootstrap.js /home/mechmind/work/tools/narwhal/engines/v8
>   cp v8/libv8.so /home/mechmind/work/tools/lib

So what i should do to get narwhal-v8 working? Seems like io-engine.so compiles correctly, but does not load.

**Comment by walisser** [comment]
If the .so is not loading you may need to add its parent directory to LD_LIBRARY_PATH environment, on Mac OS X the equivalent is DYLD_LIBRARY_PATH

**Comment by mechmind** [comment]
Looks like project is dead, so closing this issue as not relevant anymore.
